/* v109: focused menu/gameplay extension. Does not replace v107's observer or save schema.
   Online actions are server-authoritative; unavailable networking is never disguised as PvP. */
(()=>{
'use strict';
const A=window.FBArena,el=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('');
const pref=()=>{SAVE.adventure ||= {loadout:['barrage','bulwark'],mastery:{},receipts:[],goal:null,path:'assault',lastScenario:null};const p=SAVE.adventure;if(!Array.isArray(p.loadout)||p.loadout.length!==2||!p.loadout.every(s=>Object.hasOwn(A.SPELLS,s))||p.loadout[0]===p.loadout[1])p.loadout=['barrage','bulwark'];p.mastery||={};p.receipts||=[];return p;};
const API=(window.FATEBOUND_ARENA_URL||((location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1')?location.origin+'/fatebound/arena':'https://136-113-125-3.sslip.io/fatebound/arena')).replace(/\/$/,'');
let identity=null;try{identity=JSON.parse(localStorage.getItem('fatebound-arena-identity')||'null');}catch(_){}
const CLAIM_KEY='fatebound-arena-pending-claim';
async function recoverClaim(){
 let pending;try{pending=JSON.parse(localStorage.getItem(CLAIM_KEY)||'null');}catch(_){return;}
 if(!pending||pending.playerId!==identity?.playerId||N.active||TRAIN||!M?.lobby)return;
 const data=await request('/claim',{matchId:pending.matchId,shardKind:pending.shardKind});
 if(N.active||TRAIN||!M?.lobby)return;
 applyReceipt(data.receipt);localStorage.removeItem(CLAIM_KEY);onlineProfile=data.profile;updateHud();
}

let renderAt=0,busy=false,pollTimer=0,requestSerial=0,eventSeq=0,frameAt=0,lastState=null,localEngine=null,localPlayerId=null,resultShown='',epoch=0,backFocus=null,onlineProfile=null;
const N=window.FBNext={active:false,online:false,searching:false,legacyStart:false,rendering:false,warView:null,latest:null,openPrep,frame,roll:()=>action('roll',{mult:player?.mult||1,allIn:!!player?.allIn}),move:t=>action('move',{tower:t}),ultimate:()=>action('ultimate'),rally:()=>action('rally'),claim,openGifts,openExpedition,practiceScenario};
const make=(id,content)=>{let node=el(id);if(!node){node=document.createElement('div');node.id=id;node.className='overlay adventure-modal';node.hidden=true;node.innerHTML=`<section class="adventure-panel" role="dialog" aria-modal="true"><header><h2></h2><button type="button" data-dismiss aria-label="Close dialog">Close</button></header><div class="adventure-scroll"></div><footer></footer></section>`;document.body.append(node);node.querySelector('[data-dismiss]').onclick=()=>{if(N.searching)cancelQueue();else hide(id);};node.addEventListener('keydown',e=>{if(e.key==='Escape'&&!N.active){e.preventDefault();node.querySelector('[data-dismiss]').click();}if(e.key==='Tab'){const f=[...node.querySelectorAll('button:not(:disabled),select,input,a[href]')].filter(n=>n.getClientRects().length);if(f.length&&e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus();}else if(f.length&&!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus();}}});}return node;};
function show(id,title,body,footer=''){const node=make(id);node.querySelector('h2').textContent=title;node.querySelector('[role=dialog]').setAttribute('aria-label',title);node.querySelector('.adventure-scroll').innerHTML=body;node.querySelector('footer').innerHTML=footer;if(node.hidden)node._opener=document.activeElement;node.hidden=false;requestAnimationFrame(()=>node.querySelector('button:not(:disabled)')?.focus({preventScroll:true}));return node;}
function hide(id){const node=el(id);if(node)node.hidden=true;if(node?._opener?.isConnected)node._opener.focus({preventScroll:true});}
function message(id,text){const n=el(id);if(n)n.textContent=text;}
async function request(route,body,needsAuth=true){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),9000);try{const res=await fetch(API+route,{method:body===undefined?'GET':'POST',cache:'no-store',headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(needsAuth&&identity?{'Authorization':'Bearer '+identity.token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:controller.signal});let data;try{data=await res.json();}catch(_){throw Error('The arena endpoint did not return game data.');}if(!res.ok){const e=new Error(data.error||'Arena connection failed');e.status=res.status;throw e;}return data;}finally{clearTimeout(timeout);}}
async function connect(){if(!identity){identity=await request('/session',{name:'Player '+uid().slice(0,4)},false);localStorage.setItem('fatebound-arena-identity',JSON.stringify(identity));}await recoverClaim();onlineProfile=await request('/profile');return onlineProfile;}
function mastery(){const p=pref(),m=p.mastery[SAVE.char]||{assault:0,guardian:0,commander:0};const k=p.path||'assault',v=m[k]||0,levels=[50,150,350,700],rank=levels.filter(x=>v>=x).length;return {m,k,v,rank,next:levels[rank]||null,title:['Recruit','Adept','Veteran','Champion','Master'][rank]};}
function goalText(){const p=pref(),wi=p.goal;if(!Number.isInteger(wi)||!SAVE.owned.includes(wi))return 'No goal pinned. Choose an owned weapon upgrade.';const c=forgeCost(wi);return c?`${WEAPONS[wi].n} → ${TIERS[c.tier].n}: ${Math.max(0,c.gold-SAVE.gold).toLocaleString()} gold and ${Math.max(0,c.shards-(SAVE.shards[c.kind]||0))} ${SHARDS[c.kind].n} remaining.`:`${WEAPONS[wi].n}: final rarity reached.`;}
function openPrep(){if(TRAIN){toast('Save and exit training before preparing a real battle.','info');return;}if(N.active||N.searching||matchLocked())return;const p=pref(),m=mastery(),daily=A.dailyMode(Date.now());
 const box=show('adventurePrep','Prepare for battle',`<p>Choose <b>two spells</b>. They share a maximum of two charges. Triples and tower captures refill the pool.</p><div class="spell-choices">${Object.entries(A.SPELLS).map(([k,s])=>`<button data-equip="${k}" aria-pressed="${p.loadout.includes(k)}"><b>${s.name}</b><small>${s.desc}</small></button>`).join('')}</div><p id="loadoutNote" role="status">${p.loadout.map(x=>A.SPELLS[x].name).join(' + ')}</p>
 <details open><summary>Your next goal</summary><label>Pin an upgrade<select id="adventureGoal"><option value="">Choose a weapon</option>${SAVE.owned.map(w=>`<option value="${w}" ${w===p.goal?'selected':''}>${esc(WEAPONS[w].n)}</option>`).join('')}</select></label><p id="adventureGoalText">${esc(goalText())}</p><button id="adventureForge">Open Hero & armory</button></details>
 <details><summary>${CHARS[SAVE.char].n} mastery · ${m.title}</summary><p>Cosmetic ranks only. No extra combat power. Assault rewards damage; Guardian rewards absorbed damage and contested defense; Commander rewards actual rally participation and contested captures.</p><label>Track<select id="masteryPath">${['assault','guardian','commander'].map(k=>`<option ${k===m.k?'selected':''}>${k}</option>`).join('')}</select></label><p>${Object.entries(m.m).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p><p>Rank thresholds: 50 / 150 / 350 / 700. Earn a title and portrait frame. ${m.next?`${m.next-m.v} to the next ${m.k} rank.`:'Top rank earned.'}</p></details>
 <details><summary>One turning point, not constant interruptions</summary><p>At 1:45 a supply objective is announced. From 2:00–2:30, hold the marked Camp tower. The side with more control time earns +1 Focus and one spell charge per player, once. A tie awards neither side. Crown control is still the main objective.</p></details>
 ${p.lastScenario?`<details><summary>Practice your last decision</summary><p>Recreate your last tower and score deficit for 60 seconds. This is a practice scenario, not a full match replay. No resources or mastery are awarded.</p><button id="adventureLastPractice">Practice last tower</button></details>`:""}
 <details><summary>Online alpha rules</summary><p>The queue waits a full 20 seconds from the first player joining. It forms 10 vs 10, filling only the empty spots with labelled bots. Disconnected humans keep their slot; a labelled bot substitute acts until they reconnect.</p><p>Online combat uses equal level-10 common-power equipment. Your existing offline hero, inventory, Season Pass and progression are retained. Online rewards are server-validated; guest identity is stored on this device. Legacy cloud saves are not used as trusted combat stats.</p></details>
 <p class="adventure-note">Daily challenge: ${A.MODES[daily].name}. Equalized, offline practice, no resources or ranked rewards. No extra multiplayer queue.</p><p id="adventureStatus" role="status"></p>`,
 `<button id="adventureQueue" class="primary">Find 20-player battle</button><button id="adventureSolo">Solo progression</button><button id="adventureChallenge">Daily challenge</button><button id="adventureExpedition">Guild expedition</button>`);
 box.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{const k=b.dataset.equip;if(p.loadout.includes(k)){message('loadoutNote','Choose an unequipped spell to replace your oldest selection.');return;}p.loadout=[p.loadout[1],k];persist();box.querySelectorAll('[data-equip]').forEach(x=>x.setAttribute('aria-pressed',p.loadout.includes(x.dataset.equip)));message('loadoutNote',p.loadout.map(x=>A.SPELLS[x].name).join(' + '));});
 el('adventureGoal').onchange=e=>{p.goal=e.target.value===''?null:Number(e.target.value);persist();message('adventureGoalText',goalText());};el('masteryPath').onchange=e=>{p.path=e.target.value;persist();};el('adventureForge').onclick=()=>{hide('adventurePrep');showScreen('hero');};el('adventureSolo').onclick=()=>{hide('adventurePrep');N.legacyStart=true;try{openWar();if(M&&!M.ended){M.adventureLoadout=[...p.loadout];M.adventureMetrics||={absorbed:0,rallyAssists:0};M.adventureObjective||={tower:5+Math.floor(Math.random()*3),held:[0,0],at:Date.now(),status:'upcoming'};}}finally{N.legacyStart=false;}};
 if(el('adventureLastPractice'))el('adventureLastPractice').onclick=practiceScenario;el('adventureQueue').onclick=startQueue;el('adventureChallenge').onclick=()=>startPractice(daily);el('adventureExpedition').onclick=()=>{hide('adventurePrep');openExpedition();};
}
async function startQueue(){if(N.searching||N.active)return;N.searching=true;const mine=++epoch;const box=show('adventureQueueUI','Finding players',`<p id="queueCount">Connecting to the arena…</p><div id="queueTime">20</div><p>20 total slots · 10 per side.<br>Bots are added only after the 20-second lobby timer ends.</p><p id="queueError" role="status"></p>`,`<button id="queueCancel">Cancel search</button>`);el('queueCancel').onclick=cancelQueue;try{await connect();if(mine!==epoch)return;const state=await request('/queue',{char:SAVE.char,weapon:SAVE.weapon,loadout:pref().loadout});if(mine!==epoch){await request('/cancel',{}).catch(()=>{});return;}hide('adventurePrep');accept(state);poll(mine);}catch(e){if(mine!==epoch)return;N.searching=false;message('queueError',`${e.message} The live server could not be reached. Cancel search to return to offline play.`);message('queueCount','Connection required');}}
async function cancelQueue(){++epoch;clearTimeout(pollTimer);N.searching=false;try{if(identity)await request('/cancel',{});}catch(e){if(e.status===409){const st=await request('/state').catch(()=>null);if(st&&st.status==='battle'){N.searching=false;accept(st);poll(epoch);return;}}}hide('adventureQueueUI');}
function poll(mine){clearTimeout(pollTimer);if(mine!==epoch||(!N.searching&&!N.active))return;pollTimer=setTimeout(async()=>{try{const state=await request('/state');if(mine!==epoch)return;message('arenaConnection','');accept(state);}catch(e){message('queueError','Connection interrupted. Reconnecting to the same lobby…');message('arenaConnection','Reconnecting — your slot is reserved; a labelled bot may substitute.');}finally{if(mine===epoch&&(N.searching||N.active))poll(mine);}},750);}
function accept(state){lastState=state;if(state.status==='searching'){N.searching=true;N.online=true;message('queueCount',`${state.humans} / 20 human players`);message('queueTime',Math.ceil(Math.max(0,state.deadline-state.serverNow)/1000));return;}if(state.status==='idle'){if(N.searching){N.searching=false;message('queueError','The lobby expired before connection was restored. Close this dialog and search again.');}return;}if(state.status==='battle'||state.status==='complete'){N.searching=false;N.online=true;hide('adventureQueueUI');mount(state.match,identity.playerId);if(state.status==='complete')showResult(state.result,state.receipt);}}
function mount(snapshot,pid){if(N.active&&N.latest?.id===snapshot.id&&N.latest.revision>snapshot.revision)return;const ts=n=>n?n+Date.now()-snapshot.now:0;const starting=!N.active||M?.arenaId!==snapshot.id;N.active=true;N.latest=snapshot;const me=snapshot.heroes.find(h=>h.id===pid);if(!me)throw Error('This device is not in the match');const sideMap=sd=>sd===me.side?0:1;
 if(starting){hide('adventurePrep');eventSeq=0;resultShown='';N.rendering=true;newMatch(5,true);M.arena=true;M.arenaId=snapshot.id;M.campaign=true;M.lobby=false;M.training=false;M.cards=[];M.inBoss=false;BR=null;document.body.classList.add('arena-live');document.body.classList.remove('hub-mode');}
 const old=new Map(M.heroes.map(h=>[h.id,h]));M.heroes=snapshot.heroes.map(h=>{const v=old.get(h.id)||mkHero(sideMap(h.side),0,h.level,h.id===pid),wasHp=v.hp;Object.assign(v,{id:h.id,name:(h.id===pid?'You':h.name)+(h.bot?' [BOT]':h.substitute?' [BOT SUBSTITUTE]':''),side:sideMap(h.side),char:h.char,weapon:h.weapon,tier:0,weaponMult:1,level:h.level,atk:h.atk,maxHp:h.maxHp,hp:h.hp,shields:h.shieldSlots.length,shieldSlots:[...h.shieldSlots],downUntil:ts(h.downUntil),tower:h.tower,damage:h.damage,kos:h.kos,rolls:h.rolls,paidRolls:h.paidRolls,triples:h.triples,shieldsBroken:h.shieldsBroken,ult:h.ult,ultsUsed:h.ultsUsed,streak:h.streak,hot:h.hot,forcedCrits:h.forcedCrits,rampage:h.rampage,rallyJoin:0});if(wasHp>h.hp){v.hitAt=performance.now();v.hitShield=false;}return v;});
 player=M.heroes.find(h=>h.id===pid);player.gold=SAVE.gold;player.xp=SAVE.xp;player.energyAt=SAVE.energyAt;player.mult||=1;player.locked=[false,false,false];M.focus=me.focus;M.focusMax=8;M.spellSurgeUntil=ts(me.surgeUntil);M.startAt=ts(snapshot.startAt);M.endAt=ts(snapshot.endAt);M.ended=snapshot.ended;M.overtime=snapshot.phase==='overtime';M.lastTick=Date.now();
 M.towers=snapshot.towers.map(t=>({...t,dmg:me.side===0?[...t.dmg]:[t.dmg[1],t.dmg[0]],prev:t.prev<0?-1:sideMap(t.prev),defenders:[[],[]]}));M.rally=[0,1].map(sd=>{const r=snapshot.rally[sd===0?me.side:1-me.side];return r?{...r,until:ts(r.until),rollers:[...r.rollers]}:null;});M.ralliesLeft=[me.ralliesLeft,2];M.rallyCdUntil=[ts(me.rallyAt),0];M.tally=[0,1].map(sd=>{const hs=M.heroes.filter(h=>h.side===sd);return {damage:hs.reduce((n,h)=>n+h.damage,0),rolls:hs.reduce((n,h)=>n+h.rolls,0),kos:hs.reduce((n,h)=>n+h.kos,0),shields:hs.reduce((n,h)=>n+h.shieldsBroken,0)};});
 N.warView={model:2,matchVersion:3,phase:snapshot.phase==='pressure'?'day':snapshot.phase,startAt:M.startAt,pressureAt:M.startAt+120000,finaleAt:M.startAt+240000,endAt:M.endAt,control:me.side===0?[...snapshot.control]:[snapshot.control[1],snapshot.control[0]],controlDuration:snapshot.controlDuration,preview:snapshot.practice,paid:me.focusSpent};
 for(const ev of snapshot.events){if(ev.seq<=eventSeq)continue;eventSeq=ev.seq;if(!starting&&['capture','spell','ultimate','objective','phase'].includes(ev.type)){toast(ev.text,'info');if(ev.type==='objective'||ev.type==='phase')bigBanner(ev.type==='objective'?'SUPPLY OBJECTIVE':'BATTLE PHASE',ev.text);}if(!starting&&(ev.type==='roll'||ev.type==='ultimate')){const h=M.heroes.find(x=>x.id===ev.actor),target=h&&M.heroes.find(x=>x.side!==h.side&&x.tower===h.tower&&x.hp>0);if(h&&target&&h.id!==pid)try{startLunge(h,target);}catch(_){}}}
 if(starting){M.ended=false;enterTower(me.tower);N.rendering=false;M.ended=snapshot.ended;el('warPanel').hidden=true;}
 if(!snapshot.ended&&screen==='battle'){player.tower=me.tower;el('tbarName').textContent=`Tower ${M.towers[me.tower].name}`;}updateHud();paintExtras();
}
async function action(type,payload={}){if(!N.active||M?.ended||busy)return false;busy=true;const generation=epoch,matchId=M.arenaId,actionId=uid();try{let response;if(N.online)response=await request('/action',{type,...payload,matchId,actionId});else{const result=localEngine.act(localPlayerId,{type,...payload},Date.now());response={result,state:{match:localEngine.snapshot()}};}
 if(generation!==epoch||M?.arenaId!==matchId)return false;mount(response.state.match,N.online?identity.playerId:localPlayerId);
 if(type==='move'){N.rendering=true;try{enterTower(payload.tower);}finally{N.rendering=false;}}
 if(type==='roll'){const f=response.result.faces,dice=makeDiceThrow(f),t0=performance.now(),dur=Math.max(...dice.map(d=>d.duration));anim={faces:f,t0,dur,settleAt:t0+dur,dice};player.lastFaces=f;player.diceBodies=dice;rollBusy(true);SFX.roll();setTimeout(()=>{if(M?.arenaId!==matchId)return;anim=null;rollBusy(false);SFX.land();const target=M.heroes.find(h=>h.side===1&&h.tower===player.tower&&h.hp>0);if(target)try{startLunge(player,target);}catch(_){}},dur);player.allIn=false;player.mult=1;}
 if(type==='spell'||type==='ultimate'){SFX.crit();bigBanner(type==='spell'?A.SPELLS[payload.spell].name:'ULTIMATE','');}return true;
 }catch(e){toast(e.message,'warn');return false;}finally{busy=false;}}
function startPractice(mode,scenario=null){if(N.active)return;hide('adventurePrep');++epoch;N.online=false;localPlayerId='local-you';const players=Array.from({length:20},(_,i)=>({id:i?'local-bot-'+i:localPlayerId,name:i?'Bot '+i:'You',bot:i>0,char:i?i%5:SAVE.char,weapon:i?[0,1,4,5,7][i%5]:SAVE.weapon,loadout:pref().loadout}));localEngine=new A.Engine({id:'practice-'+uid(),players,now:Date.now(),seed:crypto.getRandomValues(new Uint32Array(1))[0],mode,practice:true,duration:scenario?60000:300000,scenario});mount(localEngine.snapshot(),localPlayerId);}
function practiceScenario(){startPractice('standard',pref().lastScenario||{tower:5,deficit:180});}
function applyReceipt(receipt){if(!receipt||pref().receipts.includes(receipt.id))return;atomicEconomy(()=>{const p=pref(),r=receipt.reward;p.receipts.push(receipt.id);gainGold(player,r.gold||0);if(r.fate)addEnergy(r.fate);if(r.pts)seasonAdd(r.pts);if(r.tokens)SAVE.tokens=(SAVE.tokens||0)+r.tokens;if(r.shards){const kind=receipt.shardKind||shardKindOf(receipt.id.startsWith('guild:')?SAVE.weapon:Number.isInteger(receipt.weapon)?receipt.weapon:SAVE.weapon);SAVE.shards[kind]=(SAVE.shards[kind]||0)+r.shards;}if(r.xp)gainXp(player,r.xp);const m=p.mastery[receipt.char]||={assault:0,guardian:0,commander:0};for(const k of Object.keys(m))m[k]+=receipt.mastery?.[k]||0;});}
function showResult(r,receipt){if(resultShown===r.id)return;resultShown=r.id;N.result=r;N.receipt=receipt;pref().lastScenario=r.scenario;persist();document.body.classList.remove('clash-lock','arena-live','battle-focus','ui-battle-v2','ui-map-v2');autoRoll=false;anim=null;rollBusy(false);screen='results';activateRoot('end');window.FateboundUI.setMode('post');el('end').hidden=true;const s=r.stats,best=s.absorbed>0&&s.absorbed>s.damage?'Your shields absorbed '+Math.round(s.absorbed).toLocaleString()+' damage.':s.rallyAssists>0?'Your rally drew '+s.rallyAssists+' teammates into action.':'You dealt '+Math.round(s.damage).toLocaleString()+' objective damage.';
 const b=show('adventureResult',r.draw?'Draw':r.win?'Victory':'Defeat',`<p class="arena-score">${r.score[r.side]} — ${r.score[1-r.side]} crowns</p><p>${esc(best)}</p><div class="adventure-metrics"><span><b>${s.flips}</b> contested captures</span><span><b>${s.defenseSeconds}s</b> contested defense</span><span><b>${s.spells}</b> spells cast</span></div><p>${esc(r.tip)}</p><h3>Your progress</h3><p>${r.practice?'Practice only. No currency, mastery, or ranked rewards.':r.eligible?`+${receipt?.reward.gold??r.reward.gold} gold · +${receipt?.reward.fate??r.reward.fate} Fate · +${r.reward.pts} Season Points · +${r.reward.shards} shards`:'Five Focus-spending rolls are needed for battle rewards.'}</p><p>${r.eligible?'Mastery: '+Object.entries(r.mastery).map(([k,v])=>`${k} +${v}`).join(' · '):''}</p><p>${esc(goalText())}</p>${r.eligible?`<label>Choose your shard reward<select id="resultShardChoice">${Object.keys(SHARDS).map(k=>`<option value="${k}" ${k===shardKindOf(pref().goal??SAVE.weapon)?'selected':''}>${SHARDS[k].n}</option>`).join('')}</select></label>`:''}<p id="resultError" role="status"></p>`,`<button id="resultClaim" class="primary">Claim & Home</button><button id="resultAgain">Play again</button><button id="resultLoadout">Change loadout</button><button id="resultPractice">Practice last tower</button>`);
 b.querySelector('[data-dismiss]').hidden=true;el('resultClaim').onclick=()=>claim('home');el('resultAgain').onclick=()=>claim('again');el('resultLoadout').onclick=()=>claim('loadout');el('resultPractice').onclick=()=>claim('practice');}
async function claim(next='home'){if(busy||!N.result)return;busy=true;try{let receipt=N.receipt;if(N.online){const pending={playerId:identity.playerId,matchId:N.result.id,shardKind:el('resultShardChoice')?.value};localStorage.setItem(CLAIM_KEY,JSON.stringify(pending));const r=await request('/claim',{matchId:pending.matchId,shardKind:pending.shardKind});receipt=r.receipt;onlineProfile=r.profile;}const wasOnline=N.online;++epoch;clearTimeout(pollTimer);N.active=false;N.searching=false;localEngine=null;N.warView=null;M=null;BR=null;QTE=null;giftState=null;anim=null;autoRoll=false;newMatch(5,true);if(wasOnline){applyReceipt(receipt);localStorage.removeItem(CLAIM_KEY);}hide('adventureResult');document.body.classList.remove('arena-live','clash-lock');homeHub();N.result=null;N.latest=null;N.receipt=null;if(next==='again'||next==='loadout')openPrep();if(next==='practice')practiceScenario();}catch(e){message('resultError','Rewards remain on the server. '+e.message+' Retry Claim.');}finally{busy=false;}}
function openGifts(){if(!N.active)return;const me=N.latest.heroes.find(h=>h.id===(N.online?identity.playerId:localPlayerId)),team=N.latest.heroes.filter(h=>h.side===me.side&&h.id!==me.id);const b=show('adventureGifts','Team attacks',`<p>Ready to use: ${(me.storedDamage||0).toLocaleString()} damage. Ready to send: ${me.giftDamage.toLocaleString()} damage. These combat gifts are for this match only; your older saved gifts are untouched.</p><button id="arenaUseGift" ${me.storedDamage?'':'disabled'}>Use stored team attack</button><div class="adventure-roster">${team.map(h=>`<button data-send="${esc(h.id)}" ${me.giftDamage?'':'disabled'}>${esc(h.name)}${h.bot?' · BOT':''}</button>`).join('')}</div>`);el('arenaUseGift').onclick=async()=>{if(await action('stored'))hide('adventureGifts');};b.querySelectorAll('[data-send]').forEach(x=>x.onclick=async()=>{if(await action('gift',{target:x.dataset.send}))hide('adventureGifts');});}
async function openExpedition(){if(TRAIN){toast('Save and exit training before opening the live guild.','info');return;}if(N.active||matchLocked())return;show('adventureGuild','Guild expedition','<p id="guildMessage">Connecting…</p>');try{await connect();renderExpedition();}catch(e){message('guildMessage',e.message+' Live guild expeditions require the server connection. Your offline guild remains a simulation.');}}
function renderExpedition(){const g=onlineProfile.guild;const b=show('adventureGuild','Weekly guild expedition',g?`<h3>${esc(g.name)}</h3><p>Invite code: <b>${esc(g.code)}</b> · week of ${g.week} UTC</p><p>Route: ${g.route}. One flexible shared expedition; no daily attendance requirement. Verified match contributions are capped at five per battle and 20 per day.</p><label>Guild route<select id="guildRoute" ${g.progress>0||g.leader!==onlineProfile.id?'disabled':''}>${['assault','defense','command'].map(k=>`<option ${k===g.route?'selected':''}>${k}</option>`).join('')}</select></label><p>Assault: dealt damage. Defense: damage absorbed and contested holds. Command: teammates joining rallies and contested captures.</p><div class="expedition-stages">${g.milestones.map((n,i)=>`<section><b>${['Supply camp','Fort assault','Citadel raid'][i]}</b><progress max="${n}" value="${Math.min(g.progress,n)}"></progress><small>${Math.min(g.progress,n)} / ${n} shared contribution</small><button data-exp-claim="${i}" ${g.progress<n||g.claimed.includes(i)?'disabled':''}>${g.claimed.includes(i)?'Claimed':'Claim milestone'}</button></section>`).join('')}</div><p>The final shared boss has ${Math.max(0,120-g.progress)} expedition strength remaining. Match contributions reduce it; this is an asynchronous guild objective, not simulated live players.</p><h3>Actual member contributions</h3>${g.members.map(m=>`<p>${esc(m.name)} · ${m.contribution}</p>`).join('')}<button id="guildLeave">Leave guild</button>`:`<p>Create a guild or join with a friend's code. Only real authenticated members appear in this roster. Earn shared expedition progress through completed online battles.</p><label>Guild name<input id="guildName" maxlength="32" placeholder="Name your guild"></label><button id="guildCreate">Create guild</button><label>Invite code<input id="guildCode" maxlength="16" autocomplete="off"></label><button id="guildJoin">Join guild</button>`);
 const status=document.createElement('p');status.id='guildMessage';status.setAttribute('role','status');b.querySelector('.adventure-scroll').append(status);const run=async req=>{try{const data=await request('/guild',req);onlineProfile.guild=data.guild;if(data.receipt)applyReceipt(data.receipt);renderExpedition();}catch(e){message('guildMessage',e.message);}};
 if(g){el('guildRoute').onchange=e=>run({type:'route',route:e.target.value});el('guildLeave').onclick=()=>run({type:'leave'});b.querySelectorAll('[data-exp-claim]').forEach(x=>x.onclick=()=>run({type:'claim',milestone:Number(x.dataset.expClaim)}));}else{el('guildCreate').onclick=()=>run({type:'create',name:el('guildName').value});el('guildJoin').onclick=()=>run({type:'join',code:el('guildCode').value});}}
function extras(){if(!el('adventurePrepareButton')){const b=document.createElement('button');b.id='adventurePrepareButton';b.textContent='Loadout · goals · mastery';b.onclick=openPrep;el('start').insertAdjacentElement('beforebegin',b);}if(!el('arenaExtras')){const n=document.createElement('div');n.id='arenaExtras';n.innerHTML='<small id="arenaConnection" role="status"></small><small id="arenaObjective"></small><small id="arenaDefense"></small><div id="arenaSpells"></div>';document.querySelector('#battle .rollbar').append(n);}
 if(!el('expeditionEntry')&&el('scrGuild')&&!el('scrGuild').hidden){const b=document.createElement('button');b.id='expeditionEntry';b.className='adventure-entry';b.textContent='Live guild expedition · the solo roster below is simulated';b.onclick=openExpedition;el('scrGuild').prepend(b);}const m=mastery();let badge=el('masteryBadge');if(!badge){badge=document.createElement('small');badge.id='masteryBadge';el('hubScene').append(badge);}badge.hidden=!m.rank;const badgeText=m.title+' '+CHARS[SAVE.char].n+' · '+m.k;if(badge.textContent!==badgeText)badge.textContent=badgeText;el('avatarBtn').dataset.mastery=String(m.rank);el('avatarBtn').title=CHARS[SAVE.char].n+' '+m.title+' · '+m.k+' mastery';}
function paintExtras(){extras();const activeBattle=!TRAIN&&M&&!M.ended&&!M.lobby&&screen==='battle';el('arenaExtras').hidden=!activeBattle;document.body.classList.toggle('adventure-combat',!!activeBattle);if(!activeBattle)return;const me=N.active?N.latest.heroes.find(h=>h.id===(N.online?identity.playerId:localPlayerId)):null;const choices=me?me.loadout:(M.adventureLoadout||pref().loadout),charges=me?me.spell:window.FateboundSpells?.charges()||0,key=choices.join('|');const group=el('arenaSpells');if(group.dataset.key!==key){group.dataset.key=key;group.innerHTML=choices.map(k=>`<button data-cast="${k}"><b>${A.SPELLS[k].name}</b><small></small></button>`).join('');group.querySelectorAll('[data-cast]').forEach(b=>b.onclick=()=>{if(N.active)action('spell',{spell:b.dataset.cast});else {N.rallyTapAt=performance.now();window.FateboundSpells?.cast(b.dataset.cast);}});}group.querySelectorAll('button').forEach(b=>{b.disabled=charges<=0||down(player)||busy;b.querySelector('small').textContent=charges+'/2 shared charges';});
 const o=N.active?N.latest.objective:M.adventureObjective;let text='';if(o){const elapsed=Date.now()-M.startAt;if(o.status==='warning')text=`Supply objective: Tower ${ROMAN(o.tower)} in ${Math.max(0,Math.ceil((M.startAt+120000-Date.now())/1000))}s`;else if(o.status==='active')text=`SUPPLY: Tower ${ROMAN(o.tower)} · ${Math.max(0,Math.ceil((M.startAt+150000-Date.now())/1000))}s left`;else if(o.status==='complete')text=o.winner===null?'Supply tied — no bonus':'Supply objective resolved';}message('arenaObjective',text);if(N.active){const ti=me.tower,ss=N.latest,now=ss.now;const ally=Math.ceil(Math.max(0,(ss.holds[me.side][ti]||0)-now)/1000),enemy=Math.ceil(Math.max(0,(ss.holds[1-me.side][ti]||0)-now)/1000),surge=Math.ceil(Math.max(0,me.surgeUntil-now)/1000);message('arenaDefense',[ally?'Allied protection '+ally+'s':'',enemy?'ENEMY PROTECTED '+enemy+'s':'',surge?'Arcane Surge '+surge+'s':''].filter(Boolean).join(' · '));}else message('arenaDefense','');if(N.active){const humans=N.latest.heroes.filter(h=>!h.bot).length;el('rollTrackLabel').textContent=`${N.online?'ONLINE':'OFFLINE PRACTICE'} · ${humans} human${humans===1?'':'s'} · ${20-humans} bots`;el('giftAttackCount').textContent=String((me.giftDamage?1:0)+(me.storedDamage?1:0));}}
function ROMAN(t){return ['I','II','III','IV','V','VI','VII','VIII','IX','X'][t];}
function legacyObjective(){if(N.active||TRAIN||!M?.campaign||M.ended||M.inBoss)return;const now=Date.now(),o=M.adventureObjective||=( {tower:5+Math.floor(Math.random()*3),held:[0,0],at:now,status:'upcoming'}),since=now-M.startAt,dt=Math.min(1000,now-o.at);o.at=now;
 if(o.status==='upcoming'&&since>=105000){o.status='warning';bigBanner('SUPPLY OBJECTIVE',`Tower ${ROMAN(o.tower)} activates at 2:00`);}if(o.status==='warning'&&since>=120000){o.status='active';bigBanner('SUPPLY ACTIVE',`Hold Tower ${ROMAN(o.tower)} until 2:30`);}if(o.status==='active'){const sd=towerLeader(M.towers[o.tower]);if(sd>=0)o.held[sd]+=dt;if(since>=150000){o.status='complete';o.winner=o.held[0]>o.held[1]?0:o.held[1]>o.held[0]?1:null;if(o.winner===0){addFocus(1);window.FateboundSpells?.addCharge();}if(o.winner===1){for(const h of side(1))h.buffUntil=now+5000;}bigBanner('SUPPLY RESOLVED',o.winner===null?'Tied — no bonus':o.winner===0?'+1 Focus · +1 spell charge':'Opponent secured a brief supply boost');}}}
function frame(){if(Date.now()-frameAt<200)return;frameAt=Date.now();if(localEngine&&N.active&&!localEngine.s.ended){localEngine.tick(Date.now());mount(localEngine.snapshot(),localPlayerId);if(localEngine.s.ended)showResult(localEngine.result(localPlayerId),null);}legacyObjective();paintExtras();}
// Record meaningful local contributions, not button presses. Never count guided training.
const absorb=absorbShields;absorbShields=function(h,...args){const r=absorb(h,...args);if(!N.active&&!TRAIN&&M?.campaign&&h.side===0&&r.absorbed){M.adventureMetrics||={absorbed:0,rallyAssists:0};M.adventureMetrics.absorbed+=h===player?r.absorbed:0;}return r;};
const call=callRally;callRally=function(sd,ti){const r=call(sd,ti);if(!N.active&&!TRAIN&&sd===0&&M?.rally?.[0])M.rally[0].adventureLeader=(performance.now()-(N.rallyTapAt||-10000)<150)?player.id:null;return r;};
el('rally').addEventListener('click',()=>{N.rallyTapAt=performance.now();},true);
const join=joinRally;joinRally=function(s,ti,h){const rally=M?.rally?.[s],before=rally?.rollers.length||0;const r=join(s,ti,h);if(!N.active&&!TRAIN&&s===0&&h!==player&&rally?.adventureLeader===player.id&&rally.rollers.length>before){M.adventureMetrics||={absorbed:0,rallyAssists:0};M.adventureMetrics.rallyAssists++;}return r;};
const tutorialStart=startTraining;startTraining=function(...args){if(N.active||N.searching){toast('Finish or cancel matchmaking before training.','info');return;}return tutorialStart(...args);};
const finish=finishMatch;finishMatch=function(...args){const was=M&&!M.ended&&!TRAIN&&!M.arena;const r=finish(...args);if(was&&M?.ended){const id=SAVE.war?.id||'solo-'+M.startAt,p=pref();if(player.paidRolls>=5&&!p.receipts.includes(id)){const m=p.mastery[SAVE.char]||={assault:0,guardian:0,commander:0};m.assault+=Math.min(60,Math.floor(player.damage/150));m.guardian+=Math.min(60,Math.floor((M.adventureMetrics?.absorbed||0)/100));m.commander+=Math.min(60,(M.adventureMetrics?.rallyAssists||0)*3+(player.flips||0)*2);p.receipts.push(id);persist();}p.lastScenario={tower:player.tower??5,deficit:180};setTimeout(()=>{if(!M?.ended||N.active)return;let n=el('adventureSoloSummary');if(!n){n=document.createElement('section');n.id='adventureSoloSummary';el('endRewards').insertAdjacentElement('afterend',n);}n.innerHTML=`<h3>Your next step</h3><p>${esc(goalText())}</p><p>${Math.round(player.damage).toLocaleString()} damage · ${M.adventureMetrics?.absorbed||0} absorbed · ${M.adventureMetrics?.rallyAssists||0} rally participants.</p><p>Mastery earned from actual contributions. Claim rewards, then choose a different spell pairing or practice your last tower.</p>`;},0);}return r;};
// Keep v108 dialog stacking; all other modals receive the same minimum scene layer.
for(const modal of document.querySelectorAll('.overlay:not(#setup):not(#end)')){modal.classList.add('adventure-managed-modal');modal.querySelector('.panel')?.setAttribute('role','dialog');}
pref();extras();
if(identity?.token&&identity?.playerId){
  recoverClaim().catch(e=>{console.info('Saved reward claim will retry on the next connection:',e.message);}).then(()=>request('/state')).then(state=>{
    if(N.active||N.searching||TRAIN||state.status==='idle')return;
    ++epoch;N.online=true;
    if(state.status==='searching'){
      N.searching=true;
      show('adventureQueueUI','Rejoining your lobby','<p id="queueCount"></p><div id="queueTime"></div><p>Continuing the original 20-second lobby, without adding a second player slot.</p><p id="queueError" role="status"></p>','<button id="queueCancel">Cancel search</button>');
      el('queueCancel').onclick=cancelQueue;
    }
    accept(state);poll(epoch);
  }).catch(()=>{ /* Offline Home remains usable; Find Battle retries the same stored identity. */ });
}
})();
