'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../src/arena-engine'),{Matchmaker,Store,createServer}=require('../src/arena-server');
const NOW=Date.UTC(2026,8,25,12);
function game(char=0){const e=new A.Engine({id:'audit-room',now:NOW,players:Array.from({length:20},(_,i)=>({id:'h'+i,name:'H'+i,char:i===0?char:0,weapon:0,loadout:['barrage','surge'],bot:false}))});return e;}
function paid(e,faces=['G','G','G'],i=0){const h=e.hero('h0');h.hp=h.maxHp;h.focus=8;e.faces=()=>faces.slice();return e.act(h.id,{type:'roll',mult:1},NOW+i*3000);}
function room(){let now=NOW;const mm=new Matchmaker({now:()=>now,seed:()=>1}),s=mm.createSession('Audit'),u=mm.auth(s.token);mm.join(u,{char:0,weapon:0,loadout:['barrage','surge']});now+=20000;mm.state(u);mm.tick();const e=[...mm.rooms.values()][0].engine;for(const h of e.s.heroes)h.nextBot=Infinity;return {mm,u,e,s,advance(ms){now+=ms;mm.state(u);mm.tick();},get now(){return now;}};}
function eligible(f){for(let i=0;i<5;i++){f.e.faces=()=>['G','G','G'];const h=f.e.hero(f.u.id);h.focus=8;f.mm.act(f.u,{matchId:f.e.s.id,actionId:'audit-paid-'+i,type:'roll',mult:1});f.advance(3000);}f.e.finish(f.now);f.mm.tick();}

test('ALL-IN triple gifts scale to combat power, not an unrelated 500-damage constant',()=>{const e=game(),h=e.hero('h0');h.focus=8;e.faces=()=>['F','F','F'];const r=e.act(h.id,{type:'roll',allIn:true},NOW);assert.equal(r.cost,8);assert.equal(r.mult,16);assert.equal(h.giftDamage,3000);assert.ok(h.giftDamage<=2*h.maxHp);});
test('both gift banks are capped; transfer overflow remains with sender',()=>{const e=game(),h=e.hero('h0'),ally=e.hero('h2');h.giftDamage=4000;ally.storedDamage=4000;const r=e.act(h.id,{type:'gift',target:ally.id},NOW);assert.equal(r.sent,140);assert.equal(h.giftDamage,3860);assert.equal(ally.storedDamage,4140);assert.throws(()=>e.act(h.id,{type:'gift',target:ally.id},NOW),/full/);assert.equal(h.giftDamage,3860);});
test('repeated ALL-IN gifts cannot grow the pending bank beyond two health bars',()=>{const e=game(),h=e.hero('h0');e.faces=()=>['F','F','F'];for(let i=0;i<8;i++){h.focus=8;e.act(h.id,{type:'roll',allIn:true},NOW+i*3000);}assert.equal(h.giftDamage,4140);});
test('Barrage is 1.5 times a triple sword and never refunds its charge on neutral capture',()=>{const e=game(),h=e.hero('h0');h.spell=1;h.focus=4;const r=e.act(h.id,{type:'spell',spell:'barrage'},NOW);assert.equal(r.dealt,225);assert.equal(h.spell,0);assert.equal(h.focus,4);assert.equal(h.rolls,0);assert.equal(h.credit.rolls,0);});
test('spells cannot fund spells when flipping an enemy-held objective',()=>{const e=game(),h=e.hero('h0');e.s.towers[0].dmg=[0,1];h.spell=1;e.act(h.id,{type:'spell',spell:'barrage'},NOW);assert.equal(e.leader(e.s.towers[0]),0);assert.equal(h.spell,0);assert.equal(h.focus,4);assert.equal(h.credit.flips,1);});
test('paid contested captures reward once per tower per 30 seconds',()=>{const e=game(),h=e.hero('h0'),t=e.s.towers[0];e.faces=()=>['S','S','G'];for(const [ms,expected]of [[0,1],[3000,0],[30000,1]]){t.dmg=[0,1];h.focus=4;h.spell=0;e.act(h.id,{type:'roll',mult:1},NOW+ms);assert.equal(h.spell,expected);assert.equal(h.focus,4+expected);}});
test('paid neutral captures grant no capture bonus, but triples retain their own charge',()=>{const e=game(),h=e.hero('h0');h.spell=0;paid(e,['S','S','S']);assert.equal(h.spell,1);assert.equal(h.focus,8);assert.equal(e.s.events.at(-2).rewarded,false);});
test('Rampage cannot stack free ALL-IN or high multipliers',()=>{const e=game(2),h=e.hero('h0');h.rampage=5;h.focus=0;e.faces=()=>['S','S','G'];const r=e.act(h.id,{type:'roll',mult:4,allIn:true},NOW);assert.equal(r.cost,0);assert.equal(r.mult,1);assert.equal(r.dealt,132);assert.equal(h.rampage,4);assert.equal(h.paidRolls,0);});
test('invalid multiplier and ALL-IN types reject before spending resources',()=>{for(const req of [{mult:0},{mult:'2'},{mult:null},{mult:1.5},{mult:5},{allIn:1},{allIn:'false'}]){const e=game(),h=e.hero('h0');assert.throws(()=>e.act(h.id,{type:'roll',...req},NOW));assert.equal(h.focus,4);assert.equal(h.rolls,0);}});
test('substitute actions cannot increase already-qualified human rewards or mastery',()=>{const e=game(),h=e.hero('h0');for(let i=0;i<5;i++)paid(e,['G','G','G'],i);const credit=structuredClone(h.credit);h.substitute=true;paid(e,['G','G','G'],6);h.spell=2;e.act(h.id,{type:'spell',spell:'barrage'},NOW+20000);assert.deepEqual(h.credit,credit);assert.ok(h.goldEarned>h.credit.goldEarned);e.finish(NOW+300000);const r=e.result(h.id);assert.equal(r.eligible,true);assert.equal(r.reward.gold,(r.win?180:80)+1000);assert.equal(r.stats.damage,0);assert.equal(r.mastery.assault,0);});
test('reconnected player resumes earning without retroactive bot credit',()=>{const e=game(),h=e.hero('h0');h.substitute=true;paid(e);h.substitute=false;paid(e,['G','G','G'],1);assert.equal(h.credit.rolls,1);assert.equal(h.credit.goldEarned,200);assert.equal(h.rolls,2);});
test('defense credit is not earned by absent substitutes',()=>{const e=game(),h=e.hero('h0');e.s.towers[0].dmg=[1,0];h.substitute=true;h.nextBot=Infinity;e.tick(NOW+1000);assert.equal(h.defenseSeconds,1);assert.equal(h.credit.defenseSeconds,0);h.substitute=false;e.tick(NOW+2000);assert.equal(h.credit.defenseSeconds,1);});
test('Rogue enchanted critical rolls include the advertised bonus multiplier',()=>{const e=game(1),h=e.hero('h0');h.forcedCrits=3;e.faces=()=>['C','C','G'];const r=e.act(h.id,{type:'roll',mult:1},NOW);assert.equal(r.dealt,Math.round(5*30*4.3*1.25));assert.equal(h.forcedCrits,2);});
test('Ranger Volley refunds Focus only for actual knockouts',()=>{const e=game(4),h=e.hero('h0'),foe=e.hero('h1');h.ult=100;h.focus=0;foe.hp=30;e.act(h.id,{type:'ultimate'},NOW);assert.equal(h.focus,3);assert.equal(h.kos,1);});
test('old persisted rooms retain legacy balance and remain resumable',()=>{const e=game();delete e.s.balanceVersion;const r=A.Engine.restore(e.export()),h=r.hero('h0');h.focus=8;r.faces=()=>['F','F','F'];r.act(h.id,{type:'roll',allIn:true},NOW);assert.equal(h.giftDamage,24000);h.spell=1;r.act(h.id,{type:'spell',spell:'barrage'},NOW+3000);assert.equal(h.spell,1);});
test('new room restore preserves credit and per-tower bonus cooldown',()=>{const e=game(),h=e.hero('h0');e.s.towers[0].dmg=[0,1];paid(e,['S','S','G']);const r=A.Engine.restore(e.export());assert.deepEqual(r.hero('h0').credit,h.credit);assert.deepEqual(r.hero('h0').captureRewardAt,h.captureRewardAt);assert.equal(r.s.balanceVersion,110);});
test('pending rewards remain discoverable and claimable after room cleanup',()=>{const f=room();eligible(f);const rid=f.e.s.id;f.advance(86400001);assert.equal(f.mm.rooms.size,0);assert.equal(f.mm.state(f.u).status,'idle');assert.equal(f.mm.profile(f.u).pendingRewards,1);const pending=f.mm.pendingRewards(f.u);assert.equal(pending.receipts[0].id,rid);const r=f.mm.claim(f.u,rid,'arcane');assert.equal(r.receipt.shardKind,'arcane');assert.equal(f.mm.profile(f.u).pendingRewards,0);const before=structuredClone(f.u.earned);f.mm.claim(f.u,rid,'steel');assert.deepEqual(f.u.earned,before);assert.equal(r.receipt.shardKind,'arcane');});
test('completed result is cached; later in-memory edits cannot change displayed earnings',()=>{const f=room();eligible(f);const first=f.mm.state(f.u).result;f.e.hero(f.u.id).credit.damage+=100000;f.e.hero(f.u.id).credit.goldEarned+=100000;assert.deepEqual(f.mm.state(f.u).result,first);});
test('completion receipts carry their original season and verified daily statistics',()=>{const f=room();eligible(f);const receipt=f.mm.pendingRewards(f.u).receipts[0];assert.equal(receipt.season,A.seasonKey(f.now));assert.equal(receipt.stats.paidRolls,5);assert.equal(receipt.stats.triples,5);assert.equal(receipt.balanceVersion,110);const at=receipt.at;f.advance(35*86400000);assert.equal(f.mm.claim(f.u,receipt.id).receipt.at,at);assert.equal(receipt.season,A.seasonKey(at));});
test('missing runtime room releases the slot instead of trapping the client',()=>{const f=room();f.mm.rooms.clear();assert.equal(f.mm.state(f.u).status,'idle');assert.equal(f.mm.membership.has(f.u.id),false);});
test('POST non-object JSON is rejected and pending rewards require auth',async()=>{const {server}=createServer({allowLocal:true,rateLimit:1000});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{assert.equal((await fetch(base+'/pending-rewards')).status,401);for(const body of ['null','[]','"string"']){const r=await fetch(base+'/session',{method:'POST',headers:{'Content-Type':'application/json'},body});assert.equal(r.status,400);assert.match((await r.json()).error,/object/);}const r=await fetch(base+'/health');assert.equal((await r.json()).balanceVersion,110);}finally{await new Promise(r=>server.close(r));}});
test('gift daily credit requires sending a gift, not merely rolling its symbol',()=>{const e=game(),h=e.hero('h0');paid(e,['F','F','F']);assert.equal(h.credit.giftsSent,0);e.act(h.id,{type:'gift',target:'h2'},NOW+1000);assert.equal(h.credit.giftsSent,1);e.finish(NOW+300000);assert.equal(e.result(h.id).stats.gifts,1);});
test('guild milestone grants remain pending after a lost reply and claim exactly once',()=>{
 const mm=new Matchmaker({now:()=>NOW}),session=mm.createSession('Guild audit'),u=mm.auth(session.token);
 mm.guild(u,{type:'create',name:'Audit'});const g=mm.store.data.guilds[u.guildId];g.progress=20;g.contributions[u.id]=1;
 const first=mm.guild(u,{type:'claim',milestone:0}),key=first.receipt.id;
 assert.equal(first.receipt.claimed,false);assert.equal(mm.profile(u).pendingRewards,1);assert.equal(mm.pendingRewards(u).receipts[0].id,key);
 const before=structuredClone(u.earned);mm.guild(u,{type:'claim',milestone:0});assert.deepEqual(u.earned,before);
 mm.claim(u,key);assert.equal(mm.profile(u).pendingRewards,0);mm.claim(u,key);assert.deepEqual(u.earned,before);
});
