'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createServer}=require('../src/arena-server');
async function fixture(){const {server,mm}=createServer({allowLocal:true,rateLimit:10000});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const a=mm.createSession('Native A'),b=mm.createSession('Native B');const u=mm.auth(a.token),v=mm.auth(b.token);return {server,mm,base,a,b,u,v,close:()=>new Promise(r=>server.close(r)),get:(route,token=a.token)=>fetch(base+route,{headers:{Authorization:'Bearer '+token}})};}
test('native receipt history requires authorization and is private/no-store',async()=>{const f=await fixture();try{assert.equal((await fetch(f.base+'/receipts')).status,401);const r=await f.get('/receipts');assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);assert.deepEqual(await r.json(),{receipts:[],next:null});}finally{await f.close()}});
test('receipt history is scoped to caller and read-only, including claimed records',async()=>{const f=await fixture();try{f.u.receipts.own={id:'own',at:1000,claimed:true,reward:{gold:25},shardKind:'arcane'};f.v.receipts.private={id:'private',at:1001,claimed:false,reward:{gold:999}};const economic=()=>JSON.stringify({u:f.u.receipts,v:f.v.receipts,earnedU:f.u.earned,earnedV:f.v.earned,guilds:f.mm.store.data.guilds,rooms:f.mm.store.data.rooms});const before=economic();const out=await(await f.get('/receipts?playerId='+encodeURIComponent(f.v.id))).json();assert.equal(out.receipts.length,1);assert.equal(out.receipts[0].id,'own');assert.equal(out.receipts[0].claimed,true);assert.equal(economic(),before);}finally{await f.close()}});
test('native receipt pagination has deterministic no-duplicate order',async()=>{const f=await fixture();try{for(let i=0;i<237;i++)f.u.receipts['match-'+i]={id:'match-'+i,at:1000+Math.floor(i/2),claimed:i%2===0,reward:{gold:i}};const ids=[];let after='';for(let i=0;i<4;i++){const x=await(await f.get('/receipts?limit=100'+(after?'&after='+encodeURIComponent(after):''))).json();assert.ok(x.receipts.length<=100);ids.push(...x.receipts.map(r=>r.id));if(!x.next)break;after=x.next;}assert.equal(ids.length,237);assert.equal(new Set(ids).size,237);}finally{await f.close()}});
test('invalid receipt limits/cursors reject rather than exposing unbounded history',async()=>{const f=await fixture();try{for(const q of ['limit=0','limit=101','limit=9999','limit=1.0','limit=-1','after=__proto__','after='+encodeURIComponent('a'.repeat(201))])assert.equal((await f.get('/receipts?'+q)).status,400,q);assert.equal((await f.get('/receipts?limit=1&after='+encodeURIComponent('0000000000001000:guild:2026-09-21:0'))).status,200);}finally{await f.close()}});
test('guild award can be recovered then claimed without modifying selected shard twice',async()=>{const f=await fixture();try{f.mm.guild(f.u,{type:'create',name:'Native Test'});const guild=f.mm.store.data.guilds[f.u.guildId];guild.progress=20;guild.contributions[f.u.id]=1;const first=f.mm.guild(f.u,{type:'claim',milestone:0}).receipt;let page=await(await f.get('/receipts')).json();assert.equal(page.receipts[0].claimed,false);const c=f.mm.claim(f.u,first.id,'arcane');const earned=JSON.stringify(f.u.earned);f.mm.claim(f.u,first.id,'steel');assert.equal(JSON.stringify(f.u.earned),earned);page=await(await f.get('/receipts')).json();assert.equal(page.receipts[0].claimed,true);assert.equal(page.receipts[0].shardKind,'arcane');}finally{await f.close()}});

test('same-time mixed receipt identifiers paginate in the same ordering as cursor comparison',async()=>{const f=await fixture();try{const keys=['a-b','a_b','a.b','aa','a:b','guild:2026-09-21:0','a-B'];for(const id of keys)f.u.receipts[id]={id,at:12345,claimed:true,reward:{gold:0}};let after='',seen=[];for(let i=0;i<10;i++){const page=await(await f.get('/receipts?limit=1'+(after?'&after='+encodeURIComponent(after):''))).json();seen.push(...page.receipts.map(r=>r.id));if(!page.next)break;after=page.next;}assert.deepEqual(seen,[...keys].sort());}finally{await f.close()}});
