#!/usr/bin/env python3
"""Fatebound: Siege trailer - the edit. Cuts the rendered shots together with crossfades, adds the
captions and the title card, and mixes the score under the game's own sound effects.

    python3 tools/trailer_edit.py --shots /tmp/trailer --out trailer.mp4 --fonts tools/fonts

Shots come from tools/trailer_shots.gd (Movie Maker .avi, 1920x1080 @ 30, game audio inside). The
score is generated by tools/trailer_music.py with its title hit placed on the title card.
"""
import argparse
import os
import subprocess

# (shot, caption) in order; shot lengths match LENGTH in tools/trailer_shots.gd.
CUT = [
    ("aerial", ""),
    ("captive", "THEY TOOK OUR KING."),
    ("hats", "GRAB A HAT."),
    ("assault", "STORM THE CASTLE."),
    ("whirl", "SPIN. SHIELD. SMASH."),
    ("backstab", "FIGHT DIRTY."),
    ("carry", "BRING HIM HOME."),
    ("finale", ""),
]
LENGTH = {"aerial": 5.0, "captive": 4.0, "hats": 4.5, "assault": 6.0, "whirl": 3.5, "cake": 4.0, "backstab": 4.0, "carry": 5.0, "finale": 6.0}
HEAD = 0.1          # trim the first frames (the camera settling onto the staged scene)
XF = 0.4            # crossfade
TITLE_AT = 1.2      # seconds into the finale when the title lands (on the music's hit)


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'").replace(",", "\\,")


def fade_alpha(d: float, start: float = 0.3, rise: float = 0.45, out: float = 0.45) -> str:
    return (f"if(lt(t\\,{start})\\,0\\,if(lt(t\\,{start + rise})\\,(t-{start})/{rise}\\,"
            f"if(lt(t\\,{d - out - 0.1})\\,1\\,max(0\\,({d - 0.1}-t)/{out}))))")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--shots", default="/tmp/trailer")
    ap.add_argument("--out", default="trailer.mp4")
    ap.add_argument("--fonts", default="tools/fonts")
    ap.add_argument("--music", default="", help="existing score .wav (default: generate one)")
    ap.add_argument("--song", default="", help="a song to score the trailer with (e.g. Kevin's Suno track)")
    ap.add_argument("--song-hit", type=float, default=-1.0,
                    help="time in the song (s) of the drop that should land on the title card")
    a = ap.parse_args()
    title_ttf = os.path.join(a.fonts, "Cinzel-Black.ttf")
    body_ttf = os.path.join(a.fonts, "Nunito-ExtraBold.ttf")
    durs = [LENGTH[s] - HEAD for s, _ in CUT]
    offsets = []
    acc = 0.0
    for k in range(len(CUT) - 1):
        acc += durs[k] - (XF if k > 0 else 0.0)
        offsets.append(acc - XF)
    total = sum(durs) - XF * (len(CUT) - 1)
    hit = offsets[-1] + TITLE_AT
    music = a.music or os.path.join(a.shots, "score.wav")
    if a.song:
        # Cut the song so its drop lands on the title: start = drop - title time, fade in if that's
        # mid-song, fade out at the end.
        start = max(0.0, a.song_hit - hit) if a.song_hit >= 0 else 0.0
        music = os.path.join(a.shots, "song_cut.wav")
        fade_in = 0.6 if start > 0 else 0.0
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", f"{start:.3f}", "-t", f"{total:.3f}", "-i", a.song,
                        "-af", f"afade=t=in:d={fade_in},afade=t=out:st={total - 1.4:.3f}:d=1.4" if fade_in else
                        f"afade=t=out:st={total - 1.4:.3f}:d=1.4", "-ar", "48000", "-ac", "2", music], check=True)
        # Songs can come in quiet (Kevin's Suno WAV: -23.8 LUFS, peaks -9.9 dB): one steady gain to
        # -15 LUFS (online video sits near -14; the game's SFX add on top), capped so peaks stay under -1 dB.
        meas = subprocess.run(["ffmpeg", "-v", "info", "-i", music, "-af", "loudnorm=I=-15:TP=-1:print_format=json",
                               "-f", "null", "-"], capture_output=True, text=True).stderr
        import re as _re
        li = float(_re.search(r'"input_i" : "(-?[0-9.]+)"', meas).group(1))
        tp = float(_re.search(r'"input_tp" : "(-?[0-9.]+)"', meas).group(1))
        gain = min(-15.0 - li, -1.0 - tp)
        leveled = os.path.join(a.shots, "song_level.wav")
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", music, "-af", f"volume={gain:.2f}dB", leveled], check=True)
        music = leveled
        print(f"song from {start:.2f} s: its drop at {a.song_hit:.2f} s lands on the title at {hit:.2f} s; "
              f"gain {gain:+.1f} dB ({li:.1f} LUFS -> {li + gain:.1f})")
    elif not a.music:
        here = os.path.dirname(os.path.abspath(__file__))
        subprocess.run(["python3", os.path.join(here, "trailer_music.py"), music, "--length", f"{total:.3f}", "--hit", f"{hit:.3f}"], check=True)
    inputs = []
    for s, _ in CUT:
        inputs += ["-i", os.path.join(a.shots, s + ".avi")]
    inputs += ["-i", music]
    f = []
    for k, (s, cap) in enumerate(CUT):
        d = durs[k]
        chain = f"[{k}:v]trim=start={HEAD}:duration={d},setpts=PTS-STARTPTS,fps=30,format=yuv420p,settb=AVTB"
        if cap:
            chain += (f",drawtext=fontfile='{title_ttf}':text='{esc(cap)}':fontsize=92:fontcolor=0xFFD257"
                      f":borderw=5:bordercolor=0x281806:shadowx=0:shadowy=6:shadowcolor=black@0.5"
                      f":x=(w-text_w)/2:y=h*0.74:alpha='{fade_alpha(d)}'")
        if s == "finale":
            show = f"gte(t\\,{TITLE_AT})"
            chain += (f",drawbox=x=0:y=0:w=iw:h=ih:color=black@0.25:t=fill:enable='{show}'"
                      f",drawtext=fontfile='{title_ttf}':text='FATEBOUND':fontsize=200:fontcolor=0xFFD257"
                      f":borderw=8:bordercolor=0x281806:x=(w-text_w)/2:y=h*0.26:enable='{show}'"
                      f",drawtext=fontfile='{title_ttf}':text='S I E G E':fontsize=64:fontcolor=0xF0E4C8"
                      f":x=(w-text_w)/2:y=h*0.26+230:enable='{show}'"
                      f",drawtext=fontfile='{body_ttf}':text='{esc('Storm castles. Steal hats. Rescue the King.')}'"
                      f":fontsize=50:fontcolor=white:x=(w-text_w)/2:y=h*0.64:enable='gte(t\\,{TITLE_AT + 0.6})'"
                      f",drawtext=fontfile='{body_ttf}':text='{esc('16 vs 16  ·  Online or offline with bots')}'"
                      f":fontsize=40:fontcolor=0xD8D0BE:x=(w-text_w)/2:y=h*0.64+72:enable='gte(t\\,{TITLE_AT + 1.0})'")
        f.append(chain + f"[v{k}]")
        f.append(f"[{k}:a]atrim=start={HEAD}:duration={d},asetpts=PTS-STARTPTS,aresample=48000,volume=0.55[a{k}]")
    prev_v, prev_a = "v0", "a0"
    for k in range(1, len(CUT)):
        f.append(f"[{prev_v}][v{k}]xfade=transition=fade:duration={XF}:offset={offsets[k - 1]:.3f}[vx{k}]")
        f.append(f"[{prev_a}][a{k}]acrossfade=d={XF}[ax{k}]")
        prev_v, prev_a = f"vx{k}", f"ax{k}"
    m = len(CUT)
    f.append(f"[{prev_v}]fade=t=in:st=0:d=0.8,fade=t=out:st={total - 1.0:.3f}:d=1.0[vout]")
    f.append(f"[{m}:a]aresample=48000,volume=0.9[mus]")
    f.append(f"[{prev_a}][mus]amix=inputs=2:duration=longest:normalize=0,afade=t=out:st={total - 1.2:.3f}:d=1.2,"
             f"alimiter=limit=0.95[aout]")
    cmd = ["ffmpeg", "-v", "error", "-y"] + inputs + [
        "-filter_complex", ";".join(f), "-map", "[vout]", "-map", "[aout]",
        "-c:v", "libx264", "-preset", "medium", "-crf", "18", "-pix_fmt", "yuv420p", "-r", "30",
        "-c:a", "aac", "-b:a", "192k", "-t", f"{total:.3f}", "-movflags", "+faststart", a.out]
    subprocess.run(cmd, check=True)
    print(f"wrote {a.out}: {total:.2f} s, title hit at {hit:.2f} s")


if __name__ == "__main__":
    main()
