#!/usr/bin/env python3
"""Fatebound: Siege trailer - the edit. Cuts the rendered shots together with crossfades, adds the
captions and the title card, and mixes the score under the game's own sound effects.

    python3 tools/trailer_edit.py --shots /tmp/trailer --out trailer.mp4 --fonts tools/fonts

Shots come from tools/trailer_shots.gd (Movie Maker .avi, 1920x1080 @ 30, game audio inside). The
score is generated by tools/trailer_music.py with its title hit placed on the title card.
"""
import argparse
import os
import subprocess

# (shot, caption) in order; shot lengths match LENGTH in tools/trailer_shots.gd.
CUT = [
    ("aerial", ""),
    ("captive", "THEY TOOK OUR KING."),
    ("hats", "GRAB A HAT."),
    ("assault", "STORM THE CASTLE."),
    ("whirl", "SPIN. SHIELD. SMASH."),
    ("backstab", "FIGHT DIRTY."),
    ("carry", "BRING HIM HOME."),
    ("finale", ""),
]
LENGTH = {"aerial": 5.0, "captive": 4.0, "hats": 4.5, "assault": 6.0, "whirl": 3.5, "cake": 4.0, "backstab": 4.0, "carry": 5.0, "finale": 6.0}
HEAD = 0.1          # trim the first frames (the camera settling onto the staged scene)
XF = 0.4            # crossfade
TITLE_AT = 1.2      # seconds into the finale when the title lands (on the music's hit)


# Text art (Kevin: Luckiest Guy; the game is just "Fatebound", no "Siege"): pre-rendered as transparent
# PNGs with a gold gradient, dark outline and soft shadow (ffmpeg's drawtext can't do gradients),
# then faded in/out over the footage.
FONT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "fonts")


def _gold(img, text, font, cx, y, stroke):
    from PIL import Image, ImageDraw, ImageFilter
    W, H = img.size
    bb = font.getbbox(text, stroke_width=stroke)
    w, h = bb[2] - bb[0], bb[3] - bb[1]
    x, yy = cx - w // 2 - bb[0], y - bb[1]
    sh = Image.new("L", (W, H), 0)
    ImageDraw.Draw(sh).text((x + stroke // 2, yy + stroke), text, font=font, fill=190, stroke_width=stroke, stroke_fill=190)
    sh = sh.filter(ImageFilter.GaussianBlur(max(3, stroke)))
    img.paste((0, 0, 0, 255), (0, 0), sh)
    ImageDraw.Draw(img).text((x, yy), text, font=font, fill=(46, 25, 8, 255), stroke_width=stroke, stroke_fill=(46, 25, 8, 255))
    mask = Image.new("L", (W, H), 0)
    ImageDraw.Draw(mask).text((x, yy), text, font=font, fill=255)
    grad = Image.new("RGBA", (W, H))
    gd = ImageDraw.Draw(grad)
    for y2 in range(H):
        t = min(1.0, max(0.0, (y2 - y) / max(1, h)))
        gd.line([(0, y2), (W, y2)], fill=(int(255 - 10 * t), int(236 - 80 * t), int(140 - 110 * t), 255))
    img.paste(grad, (0, 0), mask)
    return y + h


def _plain(img, text, font, cx, y, fill, stroke):
    from PIL import ImageDraw
    bb = font.getbbox(text, stroke_width=stroke)
    ImageDraw.Draw(img).text((cx - (bb[2] - bb[0]) // 2 - bb[0], y - bb[1]), text, font=font, fill=fill,
                             stroke_width=stroke, stroke_fill=(20, 14, 8, 255))


def make_overlays(folder: str) -> dict:
    from PIL import Image, ImageFont
    title_ttf = os.path.join(FONT_DIR, "LuckiestGuy-Regular.ttf")
    out = {}
    for s, cap in CUT:
        if cap:
            im = Image.new("RGBA", (1920, 1080), (0, 0, 0, 0))
            _gold(im, cap, ImageFont.truetype(title_ttf, 118), 960, 770, 9)
            out[s] = os.path.join(folder, f"ovl_{s}.png")
            im.save(out[s])
    title = Image.new("RGBA", (1920, 1080), (0, 0, 0, 0))
    _gold(title, "FATEBOUND", ImageFont.truetype(title_ttf, 250), 960, 300, 15)
    out["title"] = os.path.join(folder, "ovl_title.png")
    title.save(out["title"])
    tag = Image.new("RGBA", (1920, 1080), (0, 0, 0, 0))
    fred = os.path.join(FONT_DIR, "Fredoka-Variable.ttf")
    f1 = ImageFont.truetype(fred, 64)
    f2 = ImageFont.truetype(fred, 46)
    for f in (f1, f2):
        try:
            f.set_variation_by_name("SemiBold")
        except Exception:
            pass
    _plain(tag, "Storm castles. Steal hats. Rescue the King.", f1, 960, 690, (255, 255, 255, 255), 4)
    _plain(tag, "16 vs 16  ·  Online or offline with bots", f2, 960, 790, (230, 222, 204, 255), 3)
    out["tag"] = os.path.join(folder, "ovl_tag.png")
    tag.save(out["tag"])
    return out


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'").replace(",", "\\,")


def fade_alpha(d: float, start: float = 0.3, rise: float = 0.45, out: float = 0.45) -> str:
    return (f"if(lt(t\\,{start})\\,0\\,if(lt(t\\,{start + rise})\\,(t-{start})/{rise}\\,"
            f"if(lt(t\\,{d - out - 0.1})\\,1\\,max(0\\,({d - 0.1}-t)/{out}))))")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--shots", default="/tmp/trailer")
    ap.add_argument("--out", default="trailer.mp4")
    ap.add_argument("--fonts", default="tools/fonts")
    ap.add_argument("--music", default="", help="existing score .wav (default: generate one)")
    ap.add_argument("--song", default="", help="a song to score the trailer with (e.g. Kevin's Suno track)")
    ap.add_argument("--song-hit", type=float, default=-1.0,
                    help="time in the song (s) of the drop that should land on the title card")
    a = ap.parse_args()
    title_ttf = os.path.join(a.fonts, "Cinzel-Black.ttf")
    body_ttf = os.path.join(a.fonts, "Nunito-ExtraBold.ttf")
    durs = [LENGTH[s] - HEAD for s, _ in CUT]
    offsets = []
    acc = 0.0
    for k in range(len(CUT) - 1):
        acc += durs[k] - (XF if k > 0 else 0.0)
        offsets.append(acc - XF)
    total = sum(durs) - XF * (len(CUT) - 1)
    hit = offsets[-1] + TITLE_AT
    music = a.music or os.path.join(a.shots, "score.wav")
    if a.song:
        # Cut the song so its drop lands on the title: start = drop - title time, fade in if that's
        # mid-song, fade out at the end.
        start = max(0.0, a.song_hit - hit) if a.song_hit >= 0 else 0.0
        music = os.path.join(a.shots, "song_cut.wav")
        fade_in = 0.6 if start > 0 else 0.0
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", f"{start:.3f}", "-t", f"{total:.3f}", "-i", a.song,
                        "-af", f"afade=t=in:d={fade_in},afade=t=out:st={total - 1.4:.3f}:d=1.4" if fade_in else
                        f"afade=t=out:st={total - 1.4:.3f}:d=1.4", "-ar", "48000", "-ac", "2", music], check=True)
        # Songs can come in quiet (Kevin's Suno WAV: -23.8 LUFS, peaks -9.9 dB): one steady gain to
        # -15 LUFS (online video sits near -14; the game's SFX add on top), capped so peaks stay under -1 dB.
        meas = subprocess.run(["ffmpeg", "-v", "info", "-i", music, "-af", "loudnorm=I=-15:TP=-1:print_format=json",
                               "-f", "null", "-"], capture_output=True, text=True).stderr
        import re as _re
        li = float(_re.search(r'"input_i" : "(-?[0-9.]+)"', meas).group(1))
        tp = float(_re.search(r'"input_tp" : "(-?[0-9.]+)"', meas).group(1))
        gain = min(-15.0 - li, -1.0 - tp)
        leveled = os.path.join(a.shots, "song_level.wav")
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", music, "-af", f"volume={gain:.2f}dB", leveled], check=True)
        music = leveled
        print(f"song from {start:.2f} s: its drop at {a.song_hit:.2f} s lands on the title at {hit:.2f} s; "
              f"gain {gain:+.1f} dB ({li:.1f} LUFS -> {li + gain:.1f})")
    elif not a.music:
        here = os.path.dirname(os.path.abspath(__file__))
        subprocess.run(["python3", os.path.join(here, "trailer_music.py"), music, "--length", f"{total:.3f}", "--hit", f"{hit:.3f}"], check=True)
    inputs = []
    for s, _ in CUT:
        inputs += ["-i", os.path.join(a.shots, s + ".avi")]
    inputs += ["-i", music]
    ovl = make_overlays(a.shots)
    ov_idx = {}
    nxt = len(CUT) + 1
    for s, cap in CUT:
        if s in ovl:
            inputs += ["-loop", "1", "-framerate", "30", "-t", f"{LENGTH[s]:.3f}", "-i", ovl[s]]
            ov_idx[s] = nxt
            nxt += 1
    for key in ("title", "tag"):
        inputs += ["-loop", "1", "-framerate", "30", "-t", f"{LENGTH['finale']:.3f}", "-i", ovl[key]]
        ov_idx[key] = nxt
        nxt += 1
    f = []
    for k, (s, cap) in enumerate(CUT):
        d = durs[k]
        chain = f"[{k}:v]trim=start={HEAD}:duration={d},setpts=PTS-STARTPTS,fps=30,format=yuv420p,settb=AVTB"
        if s == "finale":
            chain += f",drawbox=x=0:y=0:w=iw:h=ih:color=black@0.25:t=fill:enable='gte(t\\,{TITLE_AT})'"
        f.append(chain + f"[b{k}]")
        if cap:
            f.append(f"[{ov_idx[s]}:v]format=rgba,setpts=PTS-STARTPTS,fade=t=in:st=0.3:d=0.45:alpha=1,"
                     f"fade=t=out:st={d - 0.55:.3f}:d=0.45:alpha=1[o{k}]")
            f.append(f"[b{k}][o{k}]overlay=0:0:shortest=1,format=yuv420p,settb=AVTB[v{k}]")
        elif s == "finale":
            f.append(f"[{ov_idx['title']}:v]format=rgba,setpts=PTS-STARTPTS,fade=t=in:st={TITLE_AT}:d=0.12:alpha=1[ot]")
            f.append(f"[{ov_idx['tag']}:v]format=rgba,setpts=PTS-STARTPTS,fade=t=in:st={TITLE_AT + 0.6}:d=0.4:alpha=1[og]")
            f.append(f"[b{k}][ot]overlay=0:0:shortest=1[bt{k}]")
            f.append(f"[bt{k}][og]overlay=0:0:shortest=1,format=yuv420p,settb=AVTB[v{k}]")
        else:
            f.append(f"[b{k}]null[v{k}]")

        f.append(f"[{k}:a]atrim=start={HEAD}:duration={d},asetpts=PTS-STARTPTS,aresample=48000,volume=0.55[a{k}]")
    prev_v, prev_a = "v0", "a0"
    for k in range(1, len(CUT)):
        f.append(f"[{prev_v}][v{k}]xfade=transition=fade:duration={XF}:offset={offsets[k - 1]:.3f}[vx{k}]")
        f.append(f"[{prev_a}][a{k}]acrossfade=d={XF}[ax{k}]")
        prev_v, prev_a = f"vx{k}", f"ax{k}"
    m = len(CUT)
    f.append(f"[{prev_v}]fade=t=in:st=0:d=0.8,fade=t=out:st={total - 1.0:.3f}:d=1.0[vout]")
    f.append(f"[{m}:a]aresample=48000,volume=0.9[mus]")
    f.append(f"[{prev_a}][mus]amix=inputs=2:duration=longest:normalize=0,afade=t=out:st={total - 1.2:.3f}:d=1.2,"
             f"alimiter=limit=0.95[aout]")
    cmd = ["ffmpeg", "-v", "error", "-y"] + inputs + [
        "-filter_complex", ";".join(f), "-map", "[vout]", "-map", "[aout]",
        "-c:v", "libx264", "-preset", "medium", "-crf", "18", "-pix_fmt", "yuv420p", "-r", "30",
        "-c:a", "aac", "-b:a", "192k", "-t", f"{total:.3f}", "-movflags", "+faststart", a.out]
    subprocess.run(cmd, check=True)
    print(f"wrote {a.out}: {total:.2f} s, title hit at {hit:.2f} s")


if __name__ == "__main__":
    main()
